// Here are the basic operation that RESTFUL api perform 
// GET IS USED FOR RETRICVE RESOURCES READ IN CRUD 

// POST IS USED FOR NEW DATA UPDATION IN DATABASE CREATE IN CRUD OPERATION 

// PUT UPDATE EXISTING DATA UPDATE IN CRUD 

// PATCH UPDATE DEXISTING DATA PARTIALLY UPDATE IN CRUD 

// DELETE REMOVES DATA FROM DATABASE DELETE IN CRUD 
